version: '2'
services:
    cms-app:
        image: cms
        external_links:
            - cms-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cms?useUnicode=true&characterEncoding=utf8&useSSL=false
    cms-mysql:
        extends:
            file: mysql.yml
            service: cms-mysql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
