version: '2'
services:
    cart-app:
        image: cart
        external_links:
            - cart-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/cart
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
    cart-postgresql:
        container_name: cart-postgresql
        image: postgres:9.5.1
        environment:
            - POSTGRES_USER=cart
            - POSTGRES_PASSWORD=
    
    cms-app:
        image: cms
        external_links:
            - cms-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cms?useUnicode=true&characterEncoding=utf8&useSSL=false
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
    cms-mysql:
        container_name: cms-mysql
        image: mysql:5.7.11
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=cms
        command: mysqld --lower_case_table_names=1 --skip-ssl
    
    gateway-app:
        image: gateway
        external_links:
            - gateway-mysql:mysql
            - gateway-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
        ports:
            - 8080:8080
    gateway-mysql:
        container_name: gateway-mysql
        image: mysql:5.7.11
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=gateway
        command: mysqld --lower_case_table_names=1 --skip-ssl
    gateway-elasticsearch:
        container_name: gateway-elasticsearch
        image: elasticsearch:1.7.5
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
    elk-elasticsearch:
        extends:
            file: elk.yml
            service: elk-elasticsearch
    elk-logstash:
        extends:
          file: elk.yml
          service: elk-logstash
    jhipster-console:
        extends:
            file: elk.yml
            service: jhipster-console
